import sqlite3
import random


conn = sqlite3.connect('bible.db')
cursor = conn.cursor()
# Generic messages for different areas of life
messages = [
    "Overall fortune is smooth but requires careful thought. Steady effort will lead you forward. Patience is key; focus on communication and teamwork. Outdoor activities are recommended to relax and prepare for upcoming challenges.",
    "Your day may feel slightly unstable, with emotions easily influenced by others. Keep a calm demeanor to avoid conflicts, and consider meditation or yoga to relax your mind.",
    "Fortune is stable today, and you will handle challenges with ease. Take time to reflect on decisions, maintain balance, and enjoy relaxing activities with loved ones.",
    "Challenges ahead may require deeper reflection. Stay patient and steady, avoid rash decisions, and engage in some outdoor relaxation to clear your mind.",
    "Today's fortune is unpredictable. You may experience emotional fluctuations, so keep your interactions calm and avoid confrontations. Relax with friends or a movie.",
    "Today is a balanced day. Approach tasks with caution and avoid impulsiveness. Plan a fun activity to unwind and reset for the week ahead.",
    "You may encounter obstacles, but persistence will see you through. Take time to think carefully and don't rush decisions. Consider going for a nature walk to clear your head.",
    "You might feel emotionally sensitive today. Take care to avoid arguments and remain low-key. Yoga or meditation can help stabilize your mood.",
    "The day will be smooth if you remain calm. Think carefully before acting and maintain a balance between work and rest. Enjoy a leisurely Sunday activity to recharge.",
    "Today’s fortune requires perseverance. Stay focused and avoid impulsive decisions. Take time to enjoy relaxing activities in the evening.",
    "Fortune is neutral today. Stay low-key and focus on managing interpersonal relationships carefully. Consider relaxing with some light exercise or a gathering with friends.",
    "Today offers a calm atmosphere. Make thoughtful decisions, keep steady, and take part in outdoor activities to boost your mood.",
    "You may face some challenges, but your inner peace will help you overcome them. Stay steady and consider going for a walk to relax.",
    "Today’s fortune is stable but requires clear thinking. Avoid rushing into decisions and focus on balancing work and rest. Plan something enjoyable to unwind.",
    "Be cautious today as emotional swings may affect your judgment. Avoid heated discussions and relax with calming activities like yoga or meditation.",
    "Your fortune today is stable, but emotional swings may arise. Be mindful of your interactions and unwind with peaceful activities like yoga or meditation.",
    "Fortune is calm and steady, but challenges will require deep thinking. Avoid rushing and focus on relaxation to clear your mind.",
    "A steady day awaits, but emotional fluctuations may challenge your patience. Stay calm, avoid conflicts, and enjoy restful activities like yoga.",
    "Today’s fortune is stable, but avoid impulsive decisions. Reflect on your goals and balance your day with moments of relaxation.",
    "Fortune is neutral; remain low-key and avoid unnecessary confrontations. Make time for a walk or light-hearted gathering to lift your spirits.",
    "Today offers a steady path. Challenges will require thoughtful responses. Take time for outdoor activities to clear your mind and prepare for tomorrow.",
    "Fortune today is stable, but emotions may fluctuate. Focus on staying balanced and enjoy relaxing activities to keep your mind clear.",
    "A calm day awaits. Avoid rushing decisions and focus on balancing your responsibilities with moments of rest and relaxation.",
    "Stay steady today; fortune is on your side. Think carefully and avoid unnecessary stress. Outdoor relaxation will help recharge your energy.",
    "Challenges may arise, but patience and inner peace will help you overcome them. Spend time outdoors or with loved ones to maintain balance.",
    "Your fortune is steady, but you may feel emotionally vulnerable. Focus on staying calm and enjoy peaceful activities like meditation to stabilize your mood.",
    "Overall fortune is calm but requires steady effort. Avoid impulsive decisions and take time to recharge with calming outdoor activities.",
    "Today’s fortune is balanced, but emotional swings are possible. Stay calm and enjoy relaxing activities like yoga or meditation.",
    "Fortune is stable, but you’ll need to focus on steady effort. Avoid emotional triggers and engage in outdoor activities to relax your mind.",
    "Stay calm today; fortune is neutral. Focus on thoughtful decisions and avoid conflict. Enjoy some relaxation with friends or in nature.",
    "Your fortune is smooth today, but challenges require clear thinking. Focus on inner peace and balance your responsibilities with restful activities.",
    "Today’s fortune is stable, but emotions may run high. Keep interactions light and focus on relaxing activities to keep your mood steady.",
    "Stay composed today; fortune is steady. Reflect carefully before acting and make time to enjoy outdoor relaxation or a light-hearted activity.",
    "Today brings stable fortune, but emotional fluctuations are possible. Keep a calm demeanor and plan restful activities to recharge.",
    "Challenges will be manageable if you remain calm. Take care to avoid emotional triggers and relax with peaceful activities like yoga or meditation.",
    "Today’s fortune is steady, but avoid rushing decisions. Take time to reflect and enjoy relaxing activities to balance your energy.",
    "Your fortune is stable, but emotional ups and downs are likely. Avoid conflicts and relax with peaceful activities like meditation or a light walk.",
    "The day offers a calm fortune. Stay steady in your efforts and avoid impulsiveness. Plan relaxing activities to keep your energy balanced.",
    "Fortune is steady, but be mindful of emotional shifts. Keep a calm approach to challenges and unwind with enjoyable, peaceful activities.",
    "Challenges may arise today, but patience will see you through. Keep a calm mindset and plan some restful activities to recharge your energy.",
    "Today’s fortune is smooth, but emotions may fluctuate. Stay mindful of your actions and take time to enjoy restful moments.",
    "Stay composed today as fortune is steady but requires clear thinking. Plan relaxing activities to balance your energy for the upcoming week.",
    "Fortune is calm, but emotional swings may challenge you. Stay patient and avoid conflicts. Engage in peaceful activities like yoga or meditation.",
    "Your fortune is stable today. Keep a balanced approach, avoid rushing decisions, and make time for enjoyable, restful activities.",
    "Fortune today is neutral. Be cautious with interactions to avoid conflicts. Relax with calming activities like meditation or yoga.",
    "A steady day awaits, but emotional challenges may arise. Keep calm and enjoy relaxing activities to help maintain balance.",
    "Today’s fortune is stable, but avoid impulsiveness. Think carefully, stay balanced, and enjoy peaceful moments to recharge your energy.",
    "Fortune is smooth today, but emotional swings are possible. Keep a calm demeanor and enjoy relaxing activities like a light walk or yoga.",
    "The day offers calm fortune. Stay steady in your efforts and avoid unnecessary stress. Plan enjoyable activities to keep your spirits high.",
    "Your fortune is neutral; avoid emotional triggers. Stay calm, think carefully, and plan some restful activities to recharge for the week ahead.",
    "Today’s fortune is steady, but be cautious with emotions. Avoid conflicts and enjoy peaceful activities like yoga or meditation to keep your mood balanced.",
    "Fortune is stable, but emotional fluctuations are possible. Stay calm and plan restful activities to maintain balance and clear your mind.",
    "Challenges may arise, but steady effort and patience will help you overcome them. Take time to relax and rejuvenate your mind with peaceful activities.",
    "Today’s fortune is stable, but emotions may fluctuate. Keep calm, avoid conflicts, and enjoy restful moments to recharge your energy."
    "Fortune is calm today, but you may experience emotional ups and downs. Keep your interactions light and focus on relaxing activities like a walk or yoga.",
    "Today offers stable fortune, but challenges may arise. Stay patient, avoid conflicts, and relax with peaceful activities to recharge your energy.",
    "Your fortune is smooth, but be cautious of emotional swings. Stay balanced in your interactions and enjoy some light-hearted fun with friends.",
    "Challenges today may require patience and steady effort. Keep calm, reflect carefully, and enjoy some relaxation to reset your mind for tomorrow.",
    "Fortune today is balanced, but avoid rushing decisions. Stay calm, think carefully, and enjoy restful moments to clear your mind.",
    "The day’s fortune is stable, but you may face emotional challenges. Stay patient, avoid arguments, and plan relaxing activities like meditation to keep your mind at ease.",
    "Today’s fortune is steady, but emotional fluctuations may affect your interactions. Stay calm and avoid unnecessary conflicts. Consider unwinding with a quiet evening.",
    "A stable day awaits, but emotions may fluctuate. Stay patient, avoid impulsive actions, and plan enjoyable activities to keep your mood balanced.",
    "Fortune today is smooth, but emotional sensitivity may arise. Stay mindful of your interactions and engage in relaxing activities like meditation or yoga.",
    "Today’s fortune is balanced. Approach challenges with patience and avoid conflicts. Plan restful activities to recharge for the coming week.",
    "Challenges today may require deeper reflection. Stay calm, think carefully, and make time for restful moments to balance your energy.",
    "Your fortune is neutral today, with emotional ups and downs likely. Stay mindful of your reactions, avoid conflicts, and unwind with peaceful activities.",
    "Today’s fortune is steady, but avoid emotional triggers. Stay calm and focused, and plan enjoyable activities to relax and reset your mood.",
    "A calm day awaits. Keep your interactions light, avoid emotional swings, and focus on relaxing activities to maintain your balance.",
    "Fortune is stable today, but emotional fluctuations may challenge you. Stay calm and patient, and enjoy relaxing moments to recharge your energy.",
    "Today offers steady fortune, but emotions may be heightened. Stay mindful of your actions, avoid conflicts, and plan some restful activities to unwind.",
    "The day’s fortune is stable. Approach challenges with patience, avoid rushing decisions, and enjoy relaxing activities to maintain a balanced mood.",
    "Today’s fortune is calm, but emotional swings may arise. Stay patient, avoid conflicts, and engage in restful activities like meditation or yoga.",
    "Challenges today will be manageable with steady effort. Keep a calm mindset, avoid emotional triggers, and enjoy peaceful activities to recharge.",
    "Fortune is neutral today. Stay calm in your interactions, avoid conflicts, and plan restful activities to reset your mind for tomorrow.",
    "A steady day awaits, but emotions may fluctuate. Keep a calm demeanor, avoid impulsive actions, and engage in relaxing activities to keep your balance.",
    "Today’s fortune is smooth, but emotional sensitivity may challenge you. Stay mindful of your reactions, avoid conflicts, and unwind with peaceful moments.",
    "Fortune today is balanced, but emotional ups and downs are likely. Stay calm, avoid conflicts, and focus on restful activities to maintain your energy.",
    "Challenges may arise today, but your inner calm will help you overcome them. Stay steady, avoid emotional triggers, and enjoy restful activities to reset.",
    "The day offers calm fortune. Stay steady in your actions, avoid rushing decisions, and plan enjoyable activities to recharge for tomorrow.",
    "Fortune today is smooth, but emotional swings may occur. Stay calm and focused, avoid conflicts, and enjoy peaceful activities to relax your mind.",
    "Challenges today may require steady effort. Stay calm, avoid impulsive actions, and plan restful moments to recharge your energy.",
    "Fortune today is neutral, but emotional fluctuations are likely. Stay mindful of your interactions, avoid conflicts, and enjoy restful activities like meditation.",
    "A steady day awaits, but emotions may be heightened. Keep a calm demeanor, avoid rushing decisions, and plan enjoyable activities to maintain your balance.",
    "Today’s fortune is stable, but emotional swings may arise. Stay patient, avoid conflicts, and engage in peaceful activities to reset your mind.",
    "Challenges will be manageable with steady effort. Keep calm, avoid emotional triggers, and plan relaxing activities to maintain your energy.",
    "Fortune today is balanced, but emotions may run high. Stay calm, avoid conflicts, and enjoy restful moments to recharge for tomorrow.",
    "Today’s fortune is neutral, but emotional fluctuations are possible. Stay mindful of your actions, avoid conflicts, and enjoy peaceful activities like yoga.",
    "Challenges today may require patience and steady effort. Stay calm, avoid emotional triggers, and unwind with peaceful activities to maintain your balance.",
    "Fortune today is stable, but emotions may fluctuate. Stay patient, avoid conflicts, and focus on relaxing activities to reset your energy.",
    "A calm day awaits, but emotional sensitivity may arise. Stay mindful of your interactions, avoid conflicts, and enjoy peaceful activities like a walk or yoga.",
    "Today offers steady fortune, but challenges may arise. Stay patient, avoid impulsive actions, and plan restful activities to recharge for tomorrow.",
    "Fortune today is neutral, but emotional ups and downs are likely. Stay calm, avoid conflicts, and unwind with peaceful moments to clear your mind.",
    "Challenges today will be manageable with steady effort. Keep a calm mindset, avoid emotional triggers, and enjoy relaxing activities to maintain your energy.",
    "Fortune is balanced today, but emotional swings may challenge you. Stay calm and patient, and plan restful activities to keep your mood steady.",
    "Today’s fortune is smooth, but emotional fluctuations may affect your interactions. Stay calm, avoid conflicts, and enjoy peaceful activities to recharge.",
    "The day’s fortune is stable, but emotions may be heightened. Stay mindful of your actions, avoid rushing decisions, and enjoy relaxing activities to reset.",
    "Fortune today is calm, but emotional swings are possible. Stay patient, avoid conflicts, and engage in peaceful activities to balance your energy.",
    "Challenges today may require deeper reflection. Stay calm, avoid impulsiveness, and plan restful activities to maintain your balance.",
    "Today’s fortune is neutral, but emotions may fluctuate. Stay mindful of your reactions, avoid conflicts, and unwind with peaceful moments.",
    "Fortune today is stable, but emotional sensitivity may arise. Stay calm and focused, avoid conflicts, and enjoy relaxing activities like yoga or meditation.",
    "A steady day awaits, but emotions may run high. Keep a calm demeanor, avoid impulsive actions, and plan relaxing activities to recharge for tomorrow.",
    "Fortune today is neutral, but emotional fluctuations are likely. Stay calm, avoid conflicts, and focus on restful moments to recharge your energy.",
    "Challenges will be manageable today if you stay calm. Avoid emotional triggers, and plan enjoyable activities to keep your mind balanced and at ease."
    "Overall fortune is stable but may require careful attention to your decisions. Focus on communication and collaboration, and consider outdoor activities to relieve stress.",
    "Today’s fortune is neutral; emotional fluctuations may occur. Maintain a calm approach in interactions, and unwind with relaxing activities like yoga or meditation.",
    "You may face challenges today, but staying grounded will help you navigate through them. Spend time in nature to clear your mind and prepare for the week ahead.",
    "Your fortune today is balanced, but impulsive decisions could lead to trouble. Take time to reflect and consider engaging in calming activities.",
    "Fortune is smooth today, but be cautious of emotional triggers. Enjoy relaxing moments with loved ones to maintain a balanced mood.",
    "Today offers a steady path, but be mindful of your emotions. Avoid conflicts and prioritize relaxation with light-hearted activities.",
    "You may feel emotionally vulnerable today. Focus on self-care, avoid heated discussions, and spend time with friends for a morale boost.",
    "Today’s fortune is stable, but challenges may arise. Stay patient, reflect carefully, and plan relaxing activities to recharge your energy.",
    "Challenges today may require deep thought and careful planning. Stay calm, take time for yourself, and avoid rushing decisions.",
    "Your fortune is steady, but emotional sensitivity may be heightened. Engage in peaceful activities to help stabilize your mood.",
    "Today brings balanced fortune. Approach challenges with patience, avoid impulsiveness, and enjoy restful activities to recharge.",
    "Fortune today is smooth; focus on steady efforts. Stay mindful of your interactions and consider taking a break to relax your mind.",
    "The day may bring emotional ups and downs. Stay calm and centered, and engage in enjoyable activities to maintain balance.",
    "You may feel a mix of emotions today. Keep a low profile to avoid conflicts and take time for calming activities like meditation or yoga.",
    "Today’s fortune is stable, but avoid rash decisions. Reflect on your choices and plan relaxing activities to help clear your mind.",
    "Overall fortune is good, but you may face some emotional challenges. Stay patient and prioritize self-care with enjoyable activities.",
    "Your fortune is balanced today. Keep a steady approach to challenges, and consider participating in outdoor activities for relaxation.",
    "Stay composed as emotional sensitivity may affect you today. Focus on mindfulness and engage in relaxing activities to maintain a peaceful mindset.",
    "Fortune is steady, but interpersonal relationships require attention. Avoid conflicts and unwind with calming activities to recharge your energy.",
    "You may feel vulnerable today. Keep calm and focus on self-care, whether through relaxation or enjoyable activities with friends.",
    "Today’s fortune is smooth, but emotional ups and downs may arise. Maintain a steady approach and plan restful moments for balance.",
    "Your fortune today is neutral. Avoid emotional triggers and keep your interactions light to maintain a positive atmosphere.",
    "Challenges may arise, but patience and steady effort will guide you through. Consider spending time in nature to clear your mind.",
    "Overall fortune is stable today, but you may need to manage your emotions carefully. Focus on relaxing activities to maintain balance.",
    "Fortune is balanced today. Avoid impulsiveness and consider taking time for yourself to recharge your energy.",
    "Today’s fortune is steady; challenges will require thoughtful responses. Focus on maintaining inner peace and unwind with enjoyable activities.",
    "You may experience emotional fluctuations today. Stay calm, avoid conflicts, and engage in peaceful activities to stabilize your mood.",
    "Today’s fortune is neutral, but challenges may require careful planning. Take time for self-reflection and prioritize relaxation.",
    "Fortune today is smooth. Keep a steady pace, avoid impulsive actions, and enjoy leisurely activities to clear your mind.",
    "Your fortune is stable, but emotional sensitivity may arise. Stay patient, focus on self-care, and plan enjoyable activities to lift your spirits.",
    "Today brings balanced fortune. Approach challenges thoughtfully, and consider engaging in outdoor activities to relieve stress.",
    "Fortune today is steady, but you may face emotional ups and downs. Stay calm and enjoy peaceful moments to maintain balance.",
    "Challenges may require deep thought and reflection today. Keep a level head, avoid conflicts, and plan relaxing activities to recharge your energy.",
    "Your fortune is neutral today. Stay mindful of emotional fluctuations and prioritize restful moments for balance.",
    "A stable day awaits, but emotional sensitivity may challenge you. Engage in calming activities to maintain a peaceful mindset.",
    "Fortune is smooth today; however, be cautious with your decisions. Take time to reflect and enjoy leisurely activities to recharge.",
    "Today’s fortune is steady, but emotional ups and downs may affect your interactions. Stay calm, avoid conflicts, and focus on restful moments.",
    "Your fortune is balanced today. Approach challenges with patience and enjoy peaceful activities to reset your mind.",
    "Fortune today is neutral, but be mindful of emotional fluctuations. Keep your interactions light and engage in relaxing activities to recharge.",
    "Stay composed today; emotional sensitivity may arise. Focus on self-care, avoid conflicts, and plan enjoyable activities to lift your spirits.",
    "Challenges may arise, but patience will help you navigate through them. Consider taking time for yourself to recharge and unwind.",
    "Your fortune is smooth today. Stay steady in your efforts and enjoy relaxing activities to maintain your mood.",
    "The day’s fortune is stable, but emotional ups and downs may affect you. Stay calm and prioritize restful activities to recharge your energy."
    "Your fortune is stable today, but external influences may cause distractions. Focus on your goals and take time to enjoy activities that bring you peace.",
    "Today may bring unexpected challenges, but your resilience will help you adapt. Keep a calm mindset and engage in creative activities to relieve stress.",
    "Fortune is neutral today. Focus on maintaining harmony in your relationships and take breaks to recharge your energy throughout the day.",
    "You may feel a bit overwhelmed, but remember to breathe and prioritize your tasks. Spend time outdoors to refresh your mind and spirit.",
    "Overall, today is a good day for collaboration. Seek input from others and approach tasks with a team spirit to achieve your goals more easily.",
    "Today’s energies support reflection and self-care. Make time for yourself and engage in activities that nurture your well-being.",
    "Fortune is steady, but avoid dwelling on past mistakes. Learn from them and move forward with a positive mindset. A walk in nature can help clear your thoughts.",
    "Your mood may fluctuate today due to external pressures. Stay grounded, avoid conflicts, and consider engaging in light exercise to uplift your spirits.",
    "Stay focused on your ambitions today. Challenges may arise, but with determination and a clear plan, you can overcome any obstacles.",
    "Fortune is stable, but it’s essential to communicate openly with loved ones. Nurturing relationships will enhance your emotional well-being.",
    "Today may bring emotional turbulence, but stay calm and focused on what matters. Spend time with friends or engage in hobbies that bring you joy.",
    "Overall, today encourages creativity. Dive into projects that inspire you, and don’t hesitate to express your ideas with others.",
    "Your day may feel slow, but that’s an opportunity to recharge. Take time to reflect on your priorities and engage in relaxing activities.",
    "Fortune is neutral today. It’s a good day to reassess your goals and take steps towards achieving them, even if they are small.",
    "You may feel the urge to socialize, and that’s beneficial. Reach out to friends or family for a fun outing to lighten your mood.",
    "Today’s energies support personal growth. Embrace opportunities for self-improvement and take time to reflect on your experiences.",
    "Challenges may arise, but stay grounded in your emotions. A calm approach will help you navigate any issues that come your way.",
    "Fortune today is stable, but external factors may cause stress. Focus on what you can control and make time for relaxation.",
    "You may feel introspective today. Use this time to evaluate your thoughts and feelings, and consider journaling to express yourself.",
    "Today is ideal for planning and strategizing. Use your analytical skills to assess your situation and devise a plan for the future.",
    "Fortune is neutral, encouraging you to take care of your physical health. Engage in activities that promote well-being and relaxation.",
    "A calm atmosphere awaits you today. Take the time to appreciate the small things in life and enjoy moments of tranquility.",
    "Today’s energies support teamwork. Collaborate with colleagues or friends to achieve common goals and foster a sense of community.",
    "Your intuition may guide you today. Trust your instincts when making decisions and don’t hesitate to seek advice from trusted sources.",
    "Challenges may require adaptability. Keep an open mind and be willing to adjust your plans as needed to overcome obstacles.",
    "Fortune is steady, encouraging you to reflect on your achievements. Celebrate your progress and acknowledge how far you’ve come.",
    "Today’s atmosphere favors positivity. Surround yourself with uplifting energy and engage in activities that inspire joy.",
    "You may feel creative sparks today. Harness this energy to work on projects that excite you or explore new hobbies.",
    "Fortune may bring unexpected news. Stay open-minded and be prepared to adapt your plans based on new information.",
    "Today encourages social interactions. Reach out to friends or family for a chat and enjoy meaningful conversations.",
    "Overall, today is a day for balance. Take breaks between tasks to avoid burnout and engage in activities that bring you peace.",
    "Fortune is steady, but avoid overthinking. Focus on living in the moment and appreciating the experiences that come your way.",
    "Today’s energies support self-expression. Don’t hesitate to share your thoughts and feelings with those around you.",
    "You may face obstacles, but your determination will see you through. Stay focused on your goals and push through challenges with resilience.",
    "Today is ideal for reflection and introspection. Take time to consider your goals and what steps you can take to achieve them.",
    "Fortune may bring emotional highs and lows. Stay grounded, and don’t hesitate to lean on friends or family for support.",
    "Today encourages creativity and self-discovery. Engage in artistic pursuits or explore new interests to enhance your self-awareness.",
    "You may feel inspired to take on new challenges. Embrace the opportunities that come your way and don’t shy away from pushing your boundaries.",
    "Today’s fortune is stable. Focus on building meaningful connections with those around you, and prioritize open communication.",
    "You may feel drawn to introspection today. Use this time to evaluate your feelings and thoughts and consider what truly matters to you.",
    "Fortune is steady, but avoid procrastination. Stay disciplined and take small steps towards your goals, even if they seem insignificant.",
    "Today’s atmosphere is calming. Engage in activities that promote relaxation, such as meditation or gentle exercise, to maintain your balance.",
    "Challenges may arise, but your perseverance will help you overcome them. Stay focused on solutions and don’t dwell on problems.",
    "Overall, today encourages nurturing relationships. Take time to connect with loved ones and express appreciation for them."
    "Your fortune is promising today, but stay alert to avoid distractions. Focus on your tasks and take breaks to maintain your energy throughout the day.",
    "Today’s energies support deep reflection. Spend time contemplating your feelings and thoughts, and consider journaling to gain clarity.",
    "Challenges may arise, but your resilience will help you navigate through. Keep a positive attitude and reach out to supportive friends for encouragement.",
    "Fortune today is steady, allowing you to take bold steps. Trust your instincts and don't hesitate to pursue new opportunities that come your way.",
    "You may feel a strong urge to connect with others today. Embrace social activities and engage in conversations that uplift your spirits.",
    "Today is an excellent day for creativity. Dive into projects that inspire you and allow your imagination to flow freely.",
    "Overall, your mood may fluctuate due to external influences. Stay grounded, practice mindfulness, and enjoy peaceful activities to balance your energy.",
    "Fortune is neutral today, encouraging you to focus on self-care. Engage in activities that promote relaxation and recharge your spirit.",
    "You may encounter unexpected challenges today. Approach them with an open mind and be ready to adapt your plans as needed.",
    "Your fortune is balanced, allowing you to nurture your relationships. Spend quality time with loved ones and strengthen your emotional connections.",
    "Today’s energies support productivity. Organize your tasks and set clear goals to maximize your efficiency throughout the day.",
    "You may feel inspired to express yourself creatively. Whether through art, writing, or music, let your creativity shine.",
    "Fortune today encourages self-reflection. Take time to evaluate your goals and think about the steps needed to achieve them.",
    "Your day may feel slow, providing a chance for relaxation. Use this time to recharge and focus on self-care activities that bring you joy.",
    "Today is ideal for collaborating with others. Teamwork will yield positive results, so embrace opportunities for partnership.",
    "Challenges may require patience and understanding. Stay calm in your interactions and seek constructive solutions to any issues that arise.",
    "Fortune today is steady, but don’t hesitate to reach out for help when needed. Your support network is there to assist you.",
    "Today’s energies favor personal growth. Embrace new learning opportunities and push yourself out of your comfort zone.",
    "You may feel emotionally sensitive today. Practice self-compassion and allow yourself the space to process your feelings.",
    "Overall, today encourages gratitude. Take time to appreciate the little things in life and express gratitude to those around you.",
    "Fortune is neutral today, inviting you to take it easy. Enjoy leisure activities that relax your mind and recharge your spirit.",
    "Your mood may be influenced by external factors. Focus on maintaining a positive mindset and surround yourself with uplifting energy.",
    "Today is a great day for planning. Take the time to organize your thoughts and outline your goals for the upcoming weeks.",
    "You may feel drawn to introspection today. Use this time to explore your thoughts and feelings, and consider journaling for self-discovery.",
    "Fortune today supports nurturing relationships. Invest time in your connections and express appreciation for those you care about.",
    "Challenges may arise, but your perseverance will guide you through. Keep a steady mindset and stay focused on your objectives.",
    "Today encourages creativity and innovation. Embrace new ideas and allow your imagination to guide you in your pursuits.",
    "Your fortune is stable, but be wary of overthinking. Focus on the present moment and enjoy the experiences life has to offer.",
    "You may feel a surge of motivation today. Use this energy to tackle projects that inspire you and set your intentions for success.",
    "Fortune is neutral, prompting you to take care of your emotional well-being. Engage in activities that bring you joy and fulfillment.",
    "Today’s energies support collaboration. Reach out to colleagues or friends to brainstorm ideas and work together on shared goals.",
    "You may feel inspired to connect with nature today. Spend time outdoors and enjoy the beauty of the world around you.",
    "Challenges today may require adaptability. Stay open to new perspectives and be willing to change your approach if needed.",
    "Your fortune is steady, allowing for meaningful connections. Engage in conversations that deepen your understanding of others.",
    "Overall, today is a day for reflection. Take time to consider your progress and celebrate your achievements, no matter how small.",
    "You may feel emotionally sensitive, so practice self-care and engage in activities that soothe your spirit.",
    "Today’s fortune invites creativity and exploration. Dive into projects that ignite your passion and allow your imagination to flourish.",
    "Challenges may arise, but your determination will help you prevail. Stay focused on your goals and take it one step at a time.",
    "Fortune is stable today, making it an excellent time for teamwork. Collaborate with others and share your insights to achieve common objectives.",
    "Today encourages self-care and relaxation. Make time for activities that nourish your mind and body, and allow yourself to unwind.",
    "You may feel a strong desire to socialize today. Embrace this energy and connect with friends or loved ones to uplift your mood.",
    "Fortune today is neutral, prompting you to reassess your priorities. Take a step back and evaluate what truly matters to you.",
    "Today is ideal for setting intentions. Reflect on your goals and take actionable steps towards achieving them, no matter how small.",
    "You may find yourself feeling inspired today. Harness this creative energy and dive into projects that excite you."
    "Today brings a wave of optimism. Focus on the positives in your life and let go of negativity to create a peaceful atmosphere.",
    "Fortune is steady today. Nurture your relationships by showing appreciation and kindness to those around you.",
    "You may feel a burst of creativity. Use this energy to explore new ideas and engage in artistic pursuits that inspire you.",
    "Challenges may arise, but don’t let them discourage you. Keep a solution-oriented mindset and stay focused on your goals.",
    "Today encourages introspection. Take time to reflect on your personal growth and set intentions for the future.",
    "Your emotional well-being is a priority today. Engage in self-care practices that promote relaxation and rejuvenation.",
    "Fortune is neutral, inviting you to explore new interests. Consider trying something new to broaden your horizons.",
    "You may feel the need to connect with others today. Reach out to friends or family for meaningful conversations.",
    "Overall, today is favorable for teamwork. Collaborate with others and share your insights to achieve common goals.",
    "Your fortune is stable, but avoid taking on too much. Prioritize your tasks and focus on quality over quantity.",
    "Today’s energies support self-expression. Don’t hesitate to share your thoughts and feelings with those around you.",
    "You may feel inspired to make changes in your life. Embrace this urge and take steps towards your goals with confidence.",
    "Fortune today encourages gratitude. Take time to acknowledge the positive aspects of your life and express appreciation.",
    "Challenges may require flexibility. Be open to adjusting your plans and adapting to new circumstances as they arise.",
    "Today is ideal for nurturing your creativity. Engage in projects that allow you to express yourself and explore new ideas.",
    "You may feel emotionally sensitive, so practice self-compassion. Take breaks to recharge and care for your emotional needs.",
    "Fortune is steady, prompting you to invest in your relationships. Take time to connect with loved ones and deepen your bonds.",
    "Overall, today encourages mindfulness. Stay present in the moment and appreciate the small joys in life.",
    "Today’s energies support personal growth. Embrace opportunities for learning and push yourself out of your comfort zone.",
    "You may encounter unexpected changes, but your adaptability will serve you well. Embrace the new and see where it leads you.",
    "Fortune today is neutral. Focus on your well-being and engage in activities that bring you joy and fulfillment.",
    "Today encourages balance. Make time for work and play to create harmony in your life and avoid burnout.",
    "You may feel drawn to introspection today. Use this time to evaluate your goals and consider what truly matters to you.",
    "Fortune is steady, but avoid overcommitting. Learn to say no when necessary and prioritize your own needs.",
    "Today’s energies favor collaboration. Team up with others to achieve shared objectives and foster a sense of community.",
    "You may feel inspired to take action today. Embrace this motivation and tackle tasks that require your attention.",
    "Challenges may arise, but your resilience will guide you through. Stay focused on solutions and don’t dwell on problems.",
    "Overall, today is a day for reflection. Take time to celebrate your achievements and acknowledge your progress.",
    "You may feel emotionally charged today. Practice grounding techniques to maintain your balance and focus on what you can control.",
    "Today’s fortune invites you to explore new perspectives. Be open to ideas from others and consider different viewpoints.",
    "Fortune today is neutral, encouraging you to take care of your mental health. Engage in activities that promote relaxation and clarity.",
    "You may feel a strong desire to socialize. Embrace this energy and connect with friends or family for uplifting interactions.",
    "Today is ideal for setting goals. Reflect on your aspirations and take actionable steps towards achieving them.",
    "You may find inspiration in unexpected places today. Stay open to new experiences and let your curiosity guide you.",
    "Challenges may require patience. Stay calm in your interactions and approach problems with a constructive mindset.",
    "Fortune is stable today, allowing for meaningful connections. Spend quality time with loved ones and express your feelings.",
    "Today’s energies support productivity. Organize your tasks and prioritize what needs to be done to maximize your efficiency.",
    "You may feel introspective today. Use this time to explore your thoughts and emotions, and consider what you truly desire.",
    "Overall, today encourages creativity. Dive into projects that excite you and allow your imagination to flourish.",
    "You may feel motivated to take on new challenges. Embrace this energy and pursue opportunities that inspire you.",
    "Today’s fortune is steady, reminding you to appreciate the present moment. Take time to enjoy the simple pleasures in life.",
    "You may encounter obstacles, but your determination will help you overcome them. Keep pushing forward and stay focused on your goals.",
    "Today encourages nurturing relationships. Invest time in your connections and express gratitude for those who support you.",
    "Fortune is neutral, inviting you to engage in self-care. Prioritize activities that promote relaxation and well-being.",
    "You may feel a burst of inspiration today. Use this energy to explore new ideas and take on projects that ignite your passion.",
    "Today brings a sense of stability. Use this time to solidify your plans and focus on long-term goals for success.",
    "Your fortune is steady, inviting you to reflect on your relationships. Consider how you can strengthen your bonds with loved ones.",
    "You may feel a surge of creativity today. Embrace this energy by engaging in artistic pursuits that inspire you and bring you joy.",
    "Challenges may present themselves, but trust your instincts to navigate through them. Your inner strength will guide you.",
    "Today encourages self-reflection. Take a moment to evaluate your progress and set intentions for what you want to achieve.",
    "Your emotional well-being is paramount today. Engage in activities that promote relaxation and make time for self-care.",
    "Fortune is neutral today, providing an opportunity to explore new interests. Don't hesitate to try something outside your comfort zone.",
    "You may feel the need for social connection today. Reach out to friends or family for meaningful conversations that uplift your spirits.",
    "Overall, today is favorable for teamwork. Collaborate with others to achieve shared objectives and strengthen your connections.",
    "Your fortune is stable, but remember not to overextend yourself. Prioritize your tasks and focus on what truly matters.",
    "Today’s energies support open communication. Share your thoughts and feelings with those around you to foster understanding.",
    "You may feel inspired to make positive changes in your life. Embrace this urge and take actionable steps towards your goals.",
    "Fortune today encourages gratitude. Take a moment to appreciate the blessings in your life and express gratitude to those who support you.",
    "Challenges may arise, but maintaining a positive mindset will help you overcome them. Stay solution-focused and adaptable.",
    "Today is ideal for nurturing your creative side. Engage in projects that allow you to express yourself freely and joyfully.",
    "You may feel emotionally sensitive, so practice self-compassion and engage in activities that nurture your spirit.",
    "Fortune is steady, prompting you to invest in your relationships. Spend quality time with loved ones to deepen your bonds.",
    "Overall, today encourages mindfulness. Stay present in the moment and find joy in the simple pleasures of life.",
    "Today’s energies support personal growth. Embrace new learning opportunities and take steps to expand your horizons.",
    "You may encounter unexpected changes, but your adaptability will help you navigate through them. Stay open-minded.",
    "Fortune today is neutral, inviting you to focus on your well-being. Engage in activities that bring you joy and fulfillment.",
    "Today encourages balance. Make time for work and leisure to create harmony in your life and avoid burnout.",
    "You may feel drawn to introspection today. Reflect on your goals and consider what truly resonates with you.",
    "Fortune is steady, reminding you to prioritize self-care. Take breaks and engage in activities that recharge your energy.",
    "Today’s energies favor collaboration. Seek opportunities to work with others and share your ideas to achieve common goals.",
    "You may feel inspired to take action today. Harness this motivation to tackle tasks that require your attention.",
    "Challenges may arise, but your resilience will help you face them. Keep pushing forward and maintain a positive outlook.",
    "Overall, today is a day for reflection. Acknowledge your progress and celebrate the small wins in your life.",
    "You may feel emotionally charged today. Use grounding techniques to stay balanced and focused on your priorities.",
    "Today’s fortune invites you to explore new perspectives. Be open to learning from others and considering different viewpoints.",
    "Fortune today is neutral, encouraging you to take care of your mental health. Engage in activities that promote relaxation and clarity.",
    "You may feel a strong desire to connect with others. Embrace this energy and reach out to friends for uplifting conversations.",
    "Today is ideal for setting intentions. Reflect on your aspirations and take actionable steps to turn them into reality.",
    "You may find inspiration in unexpected places. Stay curious and open to new experiences that ignite your passion.",
    "Challenges may require patience and understanding. Stay calm and approach problems with a constructive mindset.",
    "Fortune is stable today, allowing for meaningful connections. Spend quality time with loved ones and strengthen your relationships.",
    "Today’s energies support productivity. Organize your tasks and prioritize what needs to be done for maximum efficiency.",
    "You may feel introspective today. Use this time to explore your thoughts and emotions, and gain clarity on your desires.",
    "Overall, today encourages creativity. Dive into projects that excite you and let your imagination run wild.",
    "You may feel motivated to take on new challenges. Embrace this energy and pursue opportunities that inspire you.",
    "Today’s fortune is steady, reminding you to appreciate the present moment. Take time to enjoy life’s simple pleasures.",
    "You may encounter obstacles, but your determination will help you overcome them. Stay focused on your goals and don’t give up.",
    "Today encourages nurturing relationships. Invest time in your connections and express gratitude for the support you receive.",
    "Fortune is neutral, inviting you to engage in self-care. Prioritize activities that promote relaxation and rejuvenation.",
    "You may feel a burst of inspiration today. Use this energy to explore new ideas and take on projects that ignite your creativity.",
]


# Assign image paths
image_paths = [f'horoscope-images/{i}.jpg' for i in range(1, 41)]

horoscope_messages = []
for i, message in enumerate(messages):
    love_rating = random.randint(1, 5)
    career_rating = random.randint(1, 5)
    health_rating = random.randint(1, 5)
    wealth_rating = random.randint(1, 5)

    # Calculate overall rating as the average of the four ratings and convert to an integer
    overall_rating = int(round((love_rating + career_rating + health_rating + wealth_rating) / 4))

    horoscope_message = {
        'message': message,
        'love_rating': love_rating,
        'career_rating': career_rating,
        'health_rating': health_rating,
        'wealth_rating': wealth_rating,
        'overall_rating': overall_rating,  # Overall rating as an integer
        'lucky_color': random.choice(['Red', 'Blue', 'Green', 'Yellow', 'Purple', 'Black', 'White']),
        'lucky_number': str(random.randint(1, 99)),
        'matching_sign': random.choice(['Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo', 
                                          'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces']),
        'image_path': random.choice(image_paths)
    }
    horoscope_messages.append(horoscope_message)


# Insert records into the database and verify
for message in horoscope_messages:
    cursor.execute(f"""
        INSERT INTO generic_horoscope_messages (message, love_rating, career_rating, health_rating, wealth_rating, overall_rating, lucky_color, lucky_number, matching_sign, image_path)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
    """, (message['message'], message['love_rating'], message['career_rating'], 
          message['health_rating'], message['wealth_rating'], message['overall_rating'], 
          message['lucky_color'], message['lucky_number'], message['matching_sign'], 
          message['image_path']))

# Commit the changes
conn.commit()

# Verify by selecting all records from the table
cursor.execute("SELECT * FROM generic_horoscope_messages;")
inserted_messages = cursor.fetchall()

# Print out the inserted records for debugging
print("Inserted records:")
for record in inserted_messages:
    print(record)

# Close the connection
conn.close()